USE CRICKET
SELECT * FROM Bowling
SELECT * FROM BATTING


SELECT * FROM OneDayCenturies
SELECT * FROM T20Centuries
SELECT * FROM TestCenturies

--1. HIGHEST CENTURIES IN WHICH YEAR

SELECT TOP 1 YEAR(DATE) IN_THIS_YEAR, COUNT(RUNS) TOTAL_CENTURIES FROM OneDayCenturies GROUP BY YEAR(DATE) ORDER BY TOTAL_CENTURIES DESC

--2. LOWEST CENTURIES IN WHICH YEAR
SELECT TOP 1 YEAR(DATE) IN_THIS_YEAR, COUNT(RUNS) TOTAL_CENTURIES FROM OneDayCenturies GROUP BY YEAR(DATE) ORDER BY TOTAL_CENTURIES 

--3. BEST STRICK RATE IN WHICH YEAR

SELECT TOP 1 YEAR(DATE) SR_IN_YEAR, MAX(S_R) BEST_STRICK_RATE FROM OneDayCenturies GROUP BY YEAR(DATE) ORDER BY BEST_STRICK_RATE DESC


--4. LOWEST STRICK RATE IN WHICH YEAR

SELECT TOP 1 YEAR(DATE) SR_IN_YEAR, MAX(S_R) BEST_STRICK_RATE FROM OneDayCenturies GROUP BY YEAR(DATE) ORDER BY BEST_STRICK_RATE 

--5. TOP 5 HIGHEST CENTURIES
SELECT TOP 5 Against, Runs AS HIGHEST_SCORE_100_PLUS, Date FROM OneDayCenturies ORDER BY HIGHEST_SCORE_100_PLUS DESC

--6. WITCH WHICH COUNTRY HAS MOST CENTURIES

SELECT TOP 1 Against, COUNT(RUNS) TOTAL_CENTURIES FROM OneDayCenturies GROUP BY Against ORDER BY TOTAL_CENTURIES DESC

--7. HOW MANY CENTURIES WITH PAKISTAN
SELECT Against PAK, COUNT(RUNS) TOTAL_100 FROM OneDayCenturies WHERE Against = 'Pakistan' GROUP BY Against 

--8. HOW MANY CENTURIES WITH AUSTRALIA
SELECT Against AUS, COUNT(RUNS) TOTAL_100 FROM OneDayCenturies WHERE Against = 'Australia' GROUP BY Against 

--9. HOW MANY CENTURIES IN INDIA
SELECT H_A_N, COUNT(RUNS) TOTAL_CENTURIES_IN_INDIA FROM OneDayCenturies WHERE H_A_N = 'Home' GROUP BY H_A_N 

--10. HOW MANY CENTURIESOUTSIDE INDIA
SELECT H_A_N, COUNT(RUNS) TOTAL_CENTURIES_OUTSIDE FROM OneDayCenturies WHERE H_A_N = 'Away' GROUP BY H_A_N 

--11. TOTAL RUNS BY CENTURIES

SELECT SUM(CAST(REPLACE(REPLACE(REPLACE(RUNS,'†',' '),'*',''),'‡','') AS INT)) FROM OneDayCenturies


--12. TOTAL RUNS BY CENTURIES IN TEST, ODI AND T20

SELECT SUM(CAST(REPLACE(REPLACE(REPLACE(Runs,'*','') , '†',''), '‡','')AS INT)) TOTAL_RUNS_IN_ALL_FORMATE

FROM(
SELECT * FROM OneDayCenturies
UNION ALL
SELECT * FROM T20Centuries
UNION ALL
SELECT * FROM TestCenturies
) TOTAL_RUNS_IN_ALL_FORMATE


ALTER TABLE TestCenturies
DROP COLUMN Test



ALTER TABLE OneDayCenturies
DROP COLUMN S_R



ALTER TABLE T20Centuries
DROP COLUMN S_R
